// src/features/constants.ts

export const FINANCE_CERTIFICATION_DIRECTORY_CODE = "FINCERT";
export const FINANCE_CERTIFICATION_ENTITY_TYPE = "FINCERT";

export const CONTRACT_REQUEST_DIRECTORY_CODE = "HRCONTRAC_REQUEST";
export const CONTRACT_REQUEST_ENTITY_TYPE = "CONTRACT_REQUEST";

export const PERMISSION_DIRECTORY_CODE = "HRPERMISSION";
export const PERMISSION_ENTITY_TYPE = "PERMISSION";