// src/features/refTypeCategories.ts
//
// Catálogo centralizado de TODAS las categorías existentes en HR.ref_Types.
// Usar SIEMPRE estas constantes en vez de escribir el string de categoría
// directamente — así, si una categoría cambia de nombre en BD, se actualiza
// en un solo lugar y TypeScript marca en rojo cualquier referencia rota.
//
// Lista verificada contra la BD real (SELECT DISTINCT Category FROM HR.ref_Types).
// Docflow NO usa ref_Types (tiene su propio sistema de "directory parameters"),
// por eso DOCFLOW_* están aquí solo para completar el catálogo pero hoy no
// tienen consumidores en el frontend.

export const REF_TYPE_CATEGORIES = {
  // ── Hoja de vida / datos personales ───────────────────────────────────
  MARITAL_STATUS: "MARITAL_STATUS",
  ETHNICITY: "ETHNICITY",
  BLOOD_TYPE: "BLOOD_TYPE",
  SPECIAL_NEEDS: "SPECIAL_NEEDS",
  DISABILITY_TYPE: "DISABILITY_TYPE",
  CATASTROPHIC_ILLNESS_TYPE: "CATASTROPHIC_ILLNESS_TYPE",
  GENDER_TYPE: "GENDER_TYPE",
  SEX_TYPE: "SEX_TYPE",
  IDENTITY_TYPE: "IDENTITY_TYPE",
  RELATIONSHIP: "RELATIONSHIP",
  KNOWLEDGE_AREA: "KNOWLEDGE_AREA",
  ACADEMIC_CATEGORY: "ACADEMIC_CATEGORY",
  ACADEMIC_DEDICATION: "ACADEMIC_DEDICATION",
  ACADEMIC_LEVEL: "ACADEMIC_LEVEL",
  CV_INSTITUTION_TYPE: "CV_INSTITUTION_TYPE",
  INSTITUTION_TYPE: "INSTITUTION_TYPE",
  CV_DOCUMENT_TYPE: "CV_DOCUMENT_TYPE",
  EXPERIENCE_TYPE: "EXPERIENCE_TYPE",
  BOOK_TYPE: "BOOK_TYPE",
  BOOK_PARTIC_TYPE: "BOOK_PARTIC_TYPE",
  PUBLICATION_TYPE: "PUBLICATION_TYPE",
  JOURNAL_TYPE: "JOURNAL_TYPE",
  EVENT_TYPE: "EVENT_TYPE",
  CERTIFICATION_TYPE: "CERTIFICATION_TYPE",
  CERT_APPROVAL_TYPE: "CERT_APPROVAL_TYPE",
  TRAINING_DIRECTION: "TRAINING_DIRECTION",
  TRAINING_MODALITY: "TRAINING_MODALITY",
  LANGUAGE: "LANGUAGE",
  LANGUAGE_LEVEL: "LANGUAGE_LEVEL",
  ADDRESS_TYPE: "ADDRESS_TYPE",
  BANK_ACCOUNT_TYPE: "BANK_ACCOUNT_TYPE",

  // ── Empleo / contratos ────────────────────────────────────────────────
  CONTRACT_TYPE: "CONTRACT_TYPE",
  CONTRACT_STATUS: "CONTRACT_STATUS",
  PERSONAL_CONTRACT_TYPE: "PERSONAL_CONTRACT_TYPE",
  JOB_TYPE: "JOB_TYPE",
  LABOR_REGIME: "LABOR_REGIME",
  WORK_MODALITY: "WORK_MODALITY",
  DOCUMENT_TYPE: "DOCUMENT_TYPE",
  PROCESS_ATTACHMENT_TYPE: "PROCESS_ATTACHMENT_TYPE",
  DOCUMENT_TEMPLATE_TYPE: "DOCUMENT_TEMPLATE_TYPE",
  GENERATED_DOC_STATUS: "GENERATED_DOC_STATUS",
  AUTHORITY_TYPE: "AUTHORITY_TYPE",
  DEPARTMENT_TYPE: "DEPARTMENT_TYPE",
  DEPARTMENT_SCOPE: "DEPARTMENT_SCOPE",
  DEPARTMENT_INSTITUTIONAL_ROLE: "DEPARTMENT_INSTITUTIONAL_ROLE",
  ACCESS_MODULE_TYPE: "ACCESS_MODULE_TYPE",
  ACCESS_SCOPE_TYPE: "ACCESS_SCOPE_TYPE",

  // ── Solicitud de contratos / certificación financiera ────────────────
  CONTRACT_REQUEST_STATUS: "CONTRACT_REQUEST_STATUS",
  CONTRACT_REQUEST_PERSON_STATUS: "CONTRACT_REQUEST_PERSON_STATUS",
  CONTRACT_REQUEST_PERSON_SOURCE: "CONTRACT_REQUEST_PERSON_SOURCE",
  FIN_CERT_STATUS: "FIN_CERT_STATUS",

  // ── Acciones de personal ──────────────────────────────────────────────
  PERSONNEL_ACTION_STATUS: "PERSONNEL_ACTION_STATUS",
  PERSONNEL_ACTION_TYPE: "PERSONNEL_ACTION_TYPE",
  AP_NIVEL_GESTION: "AP_NIVEL_GESTION",
  AP_PROCESO_INSTITUCIONAL: "AP_PROCESO_INSTITUCIONAL",
  ACTION_TYPE: "ACTION_TYPE",

  // ── Asistencia / horarios / permisos ──────────────────────────────────
  PUNCH_TYPE: "PUNCH_TYPE",
  JUSTIFICATION: "JUSTIFICATION",
  JUSTIFICATION_REASON: "JUSTIFICATION_REASON",
  JUSTIFICATION_STATUS: "JUSTIFICATION_STATUS",
  PLAN_STATUS: "PLAN_STATUS",
  EMPLOYEE_PLAN_STATUS: "EMPLOYEE_PLAN_STATUS",
  CALCULATION_STATUS: "CALCULATION_STATUS",
  ROTATION_PATTERN_TYPE: "ROTATION_PATTERN_TYPE",
  SCHEDULE_CHANGE_STATUS: "SCHEDULE_CHANGE_STATUS",
  SCH_CHANGE_EMP_STATUS: "SCH_CHANGE_EMP_STATUS",
  SUBSIDY_TYPE: "SUBSIDY_TYPE",
  DEDUCTION_TYPE: "DEDUCTION_TYPE",
  MASS_VACATION_PLAN_STATUS: "MASS_VACATION_PLAN_STATUS",

  // ── Guardias ───────────────────────────────────────────────────────────
  GUARD_BLOCK_SOURCE: "GUARD_BLOCK_SOURCE",
  GUARD_BLOCK_STATUS: "GUARD_BLOCK_STATUS",
  GUARD_BLOCK_TYPE: "GUARD_BLOCK_TYPE",
  GUARD_CHANGE_STATUS: "GUARD_CHANGE_STATUS",
  FAMILY_BURDEN_STATUS: "FAMILY_BURDEN_STATUS",
  GUARD_CHANGE_TYPE: "GUARD_CHANGE_TYPE",
  GUARD_COVERAGE_TYPE: "GUARD_COVERAGE_TYPE",
  GUARD_GROUP_LEVEL_TYPE: "GUARD_GROUP_LEVEL_TYPE",
  GUARD_GROUP_STATUS: "GUARD_GROUP_STATUS",
  GUARD_LOCATION_TYPE: "GUARD_LOCATION_TYPE",
  GUARD_PLANNING_SOURCE: "GUARD_PLANNING_SOURCE",
  GUARD_PLANNING_STATUS: "GUARD_PLANNING_STATUS",
  GUARD_SHIFT_TYPE: "GUARD_SHIFT_TYPE",
  GUARD_SPECIAL_RULE_TYPE: "GUARD_SPECIAL_RULE_TYPE",
  GUARD_VACATION_PLAN_STATUS: "GUARD_VACATION_PLAN_STATUS",
  GUARD_VACATION_REQUEST_STATUS: "GUARD_VACATION_REQUEST_STATUS",
  GUARD_VACATION_REQUEST_TYPE: "GUARD_VACATION_REQUEST_TYPE",
  GUARD_VALIDATION_RESULT: "GUARD_VALIDATION_RESULT",
  GUARD_VALIDATION_SEVERITY: "GUARD_VALIDATION_SEVERITY",
  GUARD_VALIDATION_TYPE: "GUARD_VALIDATION_TYPE",

  // ── Docflow (sin consumidores hoy — completa el catálogo) ────────────
  DOCFLOW_INSTANCE_STATUSES: "DOCFLOW_INSTANCE_STATUSES",
  DOCFLOW_MOVEMENT_TYPES: "DOCFLOW_MOVEMENT_TYPES",
  DOCFLOW_PRIORITIES: "DOCFLOW_PRIORITIES",

  // ── Provisioning AD ────────────────────────────────────────────────────
  ProvisioningStatus: "ProvisioningStatus",

  // ── Autoservicio del empleado ──────────────────────────────────────────
  RESIGNATION_RETIREMENT_TYPE: "RESIGNATION_RETIREMENT_TYPE",
  EMPLOYEE_CERTIFICATE_TYPE: "EMPLOYEE_CERTIFICATE_TYPE",

  // ── Reportes SIIES (CACES, Instructivo Carga Masiva v2S) ──────────────
  SIIES_RELACION_IES: "SIIES_RELACION_IES",
  SIIES_TIPO_FUNCIONARIO: "SIIES_TIPO_FUNCIONARIO",
  SIIES_TIPO_DOCENTE_LOES: "SIIES_TIPO_DOCENTE_LOES",
  SIIES_CATEGORIA_DOCENTE_LOES: "SIIES_CATEGORIA_DOCENTE_LOES",
  SIIES_INDIGENOUS_NATIONALITY: "SIIES_INDIGENOUS_NATIONALITY",
} as const;

export type RefTypeCategory = (typeof REF_TYPE_CATEGORIES)[keyof typeof REF_TYPE_CATEGORIES];
